### PR TITLE
bug/#60-activity-list

### LINKED ISSUE #60: activities-list
fix activities list per day by itinerary section

### PR DESCRIPTION
**Pull request by MiriamIny**
closes #60

### CODE REVIEW

**Review by SNIsenberg — APPROVED** [review]
Running our site on my local, I didn't notice any bugs with the list, even with developer tools open.
However, the line you changed does look like it was wrong.
It seems that it may have somehow been working anyway. 😕

**Comment by MiriamIny** [comment]
> Running our site on my local, I didn't notice any bugs with the list, even with developer tools open. However, the line you changed does look like it was wrong. It seems that it may have somehow been working anyway. 😕

Interesting! Not sure I didn't notice the issue until @ChanaLeahNissel pointed it out, but on my local the list of activities were not showing up per day until I made the change. Either way I don't think it's hurting our program :)

File: frontend/src/pages/Trips.jsx [hunk 1]
```diff
@@ -271,6 +271,8 @@ export default function Trips() {
                     </li>
                   ))}
                 </ul>
+              ) : (
+                <div className="text-muted">No activities planned for this day.</div>
```
Comment (Temima613) [inline frontend/src/pages/Trips.jsx:275]: Maybe we should change the language here.

**Review by ChanaLeahNissel — APPROVED** [review]
